name: Lint workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install Tox
        run: pip install tox

      - name: Run Pylint
        run:  tox -e pylint-ci
