name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  normal:
    name: Usual
    uses: biolab/orange-ci-cd/.github/workflows/test-addons.yml@master
  dask:
    name: Dask
    uses: biolab/orange-ci-cd/.github/workflows/test-job.yml@master
    with:
      os: ubuntu-latest
      python-version: '3.10'
      tox_env: dask
      pyqt: '5.15.*'
